### ISSUE TITLE
Deal with `?` in beta code

### ISSUE THREAD

**Issue by whoopsedesy** [sasansom/sedes#11]
Related to #9, the new texts have `?` in their beta code in a few instances. `?` is [supposed to mean](http://www.tlg.uci.edu/encoding/quickbeta.pdf#page=3) "combining dot below," but I am given to understand it is not a real diacritical and instead marks a transcription error or omission of some sort. What's more, some of the texts use the quadrigraph `(??)` to signify an error, which if naively interpreted as beta code would mean "rough breathing, dot below, dot below, smooth breathing." The situation was discovered by a [sanity check](https://github.com/sasansom/sedes/blob/65e37f817b900856b44939816e15bf220adc2df8/src/betacode.py#L167) against duplicated diacriticals in betacode.py.

We need to do something about the `?`s. Single `?` we could just strip, on the assumption that whatever character they are annotating is actually correct. But `??` and `(??)` are likely to mark more significant errors that will cause problems with scansion whether retained or simply removed.

Perseus Hopper gets it wrong: witness line 1033 of [aratus](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A2008.01.0483) which renders `fe/rhta(??)` as φέρητἁ̣̣̓.

## `?`
* [Dion. 42.71](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A2008.01.0485%3Abook%3D42)
  * `kai\ ku/se nhri/qmoisi filh/masi la/qrios ?e(/rpwn`

## `??`
* [Argon. 1.175](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0227%3Abook%3D1%3Acard%3D156)
  * `au)to/n??t' *ai)h/thn i)de/ein shma/ntora *ko/lxwn.`
* [Argon. 1.1157](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0227%3Abook%3D1%3Acard%3D1153)
  * `nh=a bi/h|: ?? d' ou)/ ke die\c a(lo\s a)i/ssousan`
* [Argon. 1.1163](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0227%3Abook%3D1%3Acard%3D1153)
  * `*(hrakle/hs, e)ti/nasse d' a)rh??o/ta dou/rata nho/s.`
* [Argon. 1.1290](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0227%3Abook%3D1%3Acard%3D1257)
  * `h(=s' au)/tws eu)/khlos, e)pei/??u/ toi a)/rmenon h)=en`
* [Argon. 2.146](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0227%3Abook%3D2%3Acard%3D145)
  * `ei)/ pws *(hraklh=a qeo\s kai\ deu=r' e)ko/misse??.`
* [Argon. 2.1165](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0227%3Abook%3D2%3Acard%3D1125)
  * `a)lla\ ta\ me\n kai\ ??au=tis e)ni/fomen a)llh/loisin.`
* [Argon. 3.531](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0227%3Abook%3D3%3Acard%3D475)
  * `toi=si kai\ a)kama/toio p??ro\s meili/sset' a)utmh/,`
* [Argon. 4.332](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0227%3Abook%3D4%3Acard%3D294)
  * `e)n??d' e(te/rh|, plhqu\n pefulagme/noi *)ayu/rtoio,`
* [Argon. 4.1225](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0227%3Abook%3D4%3Acard%3D1168)
  * `pnoih=| e)peigo/m??i)oi prote/rw qe/on. a)lla\ ga\r ou)/pw`
* [Argon. 4.1473](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0227%3Abook%3D4%3Acard%3D1420)
  * `no/stou khdosu/nh|sin e)/bh dizh/menos ??rgw\`
* [Theoc. 15.47](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0228%3Atext%3DId.%3Apoem%3D15)
  * `e)c w(= e)n a)qana/tois o( tek??n: ou)dei\s kakoergo\s`

## `(??)`
* [Aratus 1.1033](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A2008.01.0483)
  * `mhd', o(/te nhnemi/h| ken a)ra/xnia lepta\ fe/rhta(??),`
* [Callim. Hymn 2.111](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A2008.01.0481%3Ahymn%3D2)
  * `(??)ll' h(/tis kaqarh/ te kai\ a)xra/antos a)ne/rpei)`
* [Callim. Hymn 6.94](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A2008.01.0481%3Ahymn%3D6)
  * `klai=e me\n a( ma/thr, baru\ d' e)/stenon ai( d(??) a)delfai\`
* [Dion. 4.235](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A2008.01.0485%3Abook%3D4)
  * `nho\s i)dw\n cei/no(??)s e)pibh/toras, ou(\s to/te nau=tai`
* [Dion. 10.417](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A2008.01.0485%3Abook%3D10)
  * `a)lla\ qeo\s xrai/smhsen, e)nipneu/sas de/ o(??) a)lkh\n`
* [Dion. 13.84](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A2008.01.0485%3Abook%3D13)
  * `eu)xai/ths *(ume/naios e)/xwn a)xa/rakton (??)ph/nhn,`
* [Dion. 16.63](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A2008.01.0485%3Abook%3D16)
  * `ai)/qe pe/lon no/qos o)/rnis e)u/pt(??)ros, o(/tti kai\ au(th\`
* [Dion. 16.172](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A2008.01.0485%3Abook%3D16)
  * `a(broko/mhn a)si/dhron a)na/lkida qh/le(??) morfh=|`
* [Dion. 16.175](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A2008.01.0485%3Abook%3D16)
  * `o(\s me\n to/con e)/xwn, o( de\ fa/sganon (??)dnon *)erw/twn:`
* [Dion. 23.317](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A2008.01.0485%3Abook%3D23)
  * `*zeu\s no/qon ui(=a lo/xeusen, (??)na cu/mpantas o)le/ssh|`
* [Dion. 25.268](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A2008.01.0485%3Abook%3D25)
  * `*bakxia/dos su/riggos a)ge/straton (??)xn a)kou/sw`
* [Dion. 26.270](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A2008.01.0485%3Abook%3D26)
  * `ma/ntis e)pessome/nwn e)baru/neto pouluto/(??)os su=s,`
* [Dion. 27.337](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A2008.01.0485%3Abook%3D27)
  * `toi=si *fo/bos kai\ *dei=mos o(me/mporoi, o(??)si kai\ au)th\`
* [Dion. 28.63](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A2008.01.0485%3Abook%3D28)
  * `au)ti/ka d' e)k koleoi=o *koru/mbasos (??)or e)ru/ssas`
* [Dion. 32.56](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A2008.01.0485%3Abook%3D32)
  * `tou=ton e)gw) kale/ousa pali/ndrom(??)s e)nqa/de bai/nw:`
* [Dion. 33.336](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A2008.01.0485%3Abook%3D33)
  * `o(??) me dieptoi/hsen e)rwmane/wn e)nosi/xqwn,`
* [Dion. 44.220](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A2008.01.0485%3Abook%3D44)
  * `u(mete/rwn (??)ti gai=a futw=n w)di=na pepai/nei`
* [Dion. 44.306](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A2008.01.0485%3Abook%3D44)
  * `xa/rmati d' (??)bh/sas se/qen ui(e/os ei(/neka nu/mfhs`
* [Quint. Smyrn. 2.82](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A2008.01.0490%3Abook%3D2)
  * `*pouluda/mas: ou) ga/r oi( e)nanti/on a(/zet' a)(??)sai`
* [Quint. Smyrn. 3.225](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A2008.01.0490%3Abook%3D3)
  * `kapnou= u(po\ r((??)h=s h)d' a)ne/ros, a)ll' a)/ra kai\ w(\s`
* [Quint. Smyrn. 4.424](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A2008.01.0490%3Abook%3D4)
  * `u(drhlh=s kape/toio ma/l' a)gxo/qi thleqa/(??)nta`
* [Quint. Smyrn. 8.413](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A2008.01.0490%3Abook%3D8)
  * `o(/n de/mas, ou)de/ oi( i)o\s e)pi\ xro/a kalo\n i)/ayen(??)`
* [Quint. Smyrn. 12.164](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A2008.01.0490%3Abook%3D12)
  * `ou)rano/qen fore/onto poti\ xqo/na: toi=si d)(??)u(/p' ai)qh\r`

**Comment by whoopsedesy** [comment]
@sasansom has fixes for these occurrences of `?`. I've just pushed 10d7c9f which will raise an error at any attempt to process `?` in beta code, which will prevent silent errors in the future.

**Comment by sasansom** [comment]
I just fixed and pushed the xml files.

**Comment by sasansom** [comment]
Commit f4e25c8 fixes "r()" to "r('" in the argonautica.

**Comment by sasansom** [comment]
Commit a86b485 fixes one incorrect ') ' .
