### ISSUE TITLE
Add lemma to CSV

### ISSUE THREAD

**Issue by whoopsedesy** [sasansom/sedes#2]
Include a (most common?) lemma for each word in the CSV.

CTLK has a lemmatizer for Greek:
http://docs.cltk.org/en/stable/greek.html#lemmatization

Not sure what Perseus Hopper uses.

**Comment by sasansom** [comment]
It looks like [Perseus uses Morpheus](https://wiki.digitalclassicist.org/Morpheus):

https://github.com/gcelano/LemmatizedAncientGreekXML/tree/master/Morpheus

**Comment by sasansom** [comment]
Here is Perseus' lemma dictionary (extracted via CTLK): https://github.com/cltk/greek_lexica_perseus/blob/master/greek-lemmata.txt
