### ISSUE TITLE
Restore quotations to nonnusdionysiaca.xml using `q` elements

### ISSUE THREAD

**Issue by whoopsedesy** [sasansom/sedes#26]
b0c533e7afcf56ac42ecc0c55342780ff6fdec9c and 7136b753ccf63dd8280c9c4c16cc40098ac3c30c removed quotation marks that were improperly marked up using `'` characters from corpus/nonnusdionysiaca.xml. This avoids the problem of interpreting `'` as a word character, but it of course loses the location of quotations. The quotations should be restored, using `q` elements instead of `'` characters. This TEI file uses `lb` to separate lines, so there's no problem with overlapping markup.

Past state:
```
<lb rend="displayNum" n="459" />'sh/meron *)aktai/wna/ tis h(/rpasen, ei)/pate, pe/trai,
<lb rend="displayNum" n="460" />ph=| dro/mon a)mfie/pei kemadosso/on, ei)/pate, *nu/mfai.' 
```

Current state:
```
<lb rend="displayNum" n="459" />sh/meron *)aktai/wna/ tis h(/rpasen, ei)/pate, pe/trai,
<lb rend="displayNum" n="460" />ph=| dro/mon a)mfie/pei kemadosso/on, ei)/pate, *nu/mfai.
```

Desired state:
```
<lb rend="displayNum" n="459" /><q>sh/meron *)aktai/wna/ tis h(/rpasen, ei)/pate, pe/trai,
<lb rend="displayNum" n="460" />ph=| dro/mon a)mfie/pei kemadosso/on, ei)/pate, *nu/mfai.</q>
```

**Comment by whoopsedesy** [comment]
This still needs a little fix. Quotations should begin with `<q>` but end with `</q>` (note the slash). `<q>` is a so-called [start tag](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/SG.html#SG131) and `</q>` is an end tag. Using only start tags semantically means nesting quotations within quotations within quotations.

I'm actually surprised that our Beautiful Soup–based parser doesn't raise an error on this markup—it seems to close a `<q>` with an implicit `</q>` whenever a parent element ends, which prevent imbalanced tags. You can check for syntax errors like this using a number of XML validation tools—I used [xmllint](http://xmlsoft.org/xmllint.html) but I'm not sure if that's installed by default on macOS. You can do this without needing to install anything:
```
python3 -c 'import xml.dom.minidom; xml.dom.minidom.parse(open("corpus/nonnusdionysiaca.xml"))'
```
If there is no error, it will output nothing. If there is an error, it will output something that ends with something like
```
xml.parsers.expat.ExpatError: mismatched tag: line 1019, column 2
```
The error may not be exactly on the line reported; it's reporting where the putative nested quotation ends, not where it begins. This one is actually on line 965 (second `<q>` should be `</q>`):
```
<lb rend="displayNum" n="304" /><q>lu/sas desmo\n *)/arhos e)keu/qeto de/smios *(ermh=s.<q>
```

**Comment by whoopsedesy** [comment]
> I'm actually surprised that our Beautiful Soup–based parser doesn't raise an error on this markup—it seems to close a `<q>` with an implicit `</q>` whenever a parent element ends, which prevents imbalanced tags.

Note to self: this is because bs4 sets [`recover=True`](https://lxml.de/parsing.html#parser-options) on its internal lxml parser:
https://bazaar.launchpad.net/~leonardr/beautifulsoup/bs4/view/598/bs4/builder/_lxml.py#L100
https://bazaar.launchpad.net/~leonardr/beautifulsoup/bs4/view/598/bs4/builder/_lxml.py#L114

**Comment by sasansom** [comment]
Ah, thanks for pointing this out. I've now changed the end quotes to `</q>`. I also noticed a couple of opening quotes (`<q>`) that were lacking and added them at corpus/nonnusdionysiaca.xml code lines 7686, 11970, and 17812.
