### ISSUE TITLE
Undo the removal of a `note` element

### ISSUE THREAD

**Issue by whoopsedesy** [sasansom/sedes#28]
I happened to be looking at some of the diffs for #11 and spotted
https://github.com/sasansom/sedes/commit/b0b399d13d17540af7d943c64534b88fc5987c3a#diff-3d7ec391734440543298d6a2bc0eeebcb99b03c8750a1a5f32d80f29dea966e5L400-R400. The first diff hunk removes a `note` element that should be restored.

**Comment by sasansom** [comment]
It appears this has been [undone](https://github.com/sasansom/sedes/blob/549bc25f7296187ec9692fba5da6717ec17329fb/corpus/aratus.xml#L400) at some point, though I'm not sure by what commit.

**Comment by whoopsedesy** [comment]
Good call; it was done by you in 67d7b719be9791f79ee9b645217a5012ff84429f.

If you're curious about how to find information about past changes: [`git log`](https://www.git-scm.com/docs/git-log) can show the log of changes to a single file (the `$` represents the command prompt):
```
$ git log corpus/aratus.xml 
commit d6dbac5837ef2be55cbe2a0dd47e8cec762e49ec
Author: Stephen Sansom <sasansom@gmail.com>
Date:   Fri May 22 10:55:48 2020 -0400

    fixes to corpus/aratus.xml

commit 0441279853bf27446df65223f78da61bfbe3118e
Author: Stephen Sansom <sasansom@gmail.com>
Date:   Thu Apr 9 15:11:43 2020 -0400

    fixes to text of corpus/aratus.xml.

commit 67d7b719be9791f79ee9b645217a5012ff84429f
Author: Stephen Sansom <sasansom@gmail.com>
Date:   Mon Mar 16 07:53:50 2020 -0400

    Beta code fixes in aratus.xml continued (#11)

commit b0b399d13d17540af7d943c64534b88fc5987c3a
Author: Stephen Sansom <sasansom@gmail.com>
Date:   Mon Mar 16 01:43:18 2020 -0400

    Beta code fixes in aratus.xml (#11)

commit de40680ae0747232ab1a40818e65fdbade6b8e6e
Author: Stephen Sansom <sasansom@gmail.com>
Date:   Thu Mar 12 21:13:16 2020 -0400

    Add Aratus Phaenomena
```

[`git blame`](https://www.git-scm.com/docs/git-blame) shows when each line was last modified and by whom:
```
$ git blame corpus/aratus.xml
...
de40680a (Stephen Sansom 2020-03-12 21:13:16 -0400  398) <lb rend="displayNum" n="298" />h(/meq' e)p' ai)gialou\s tetramme/noi: oi( d' e)/ti po/rsw
de40680a (Stephen Sansom 2020-03-12 21:13:16 -0400  399) <lb rend="displayNum" n="299" />klu/zontai: o)li/gon de\ dia\ cu/lon *)/ai+d' e)ru/kei.
67d7b719 (Stephen Sansom 2020-03-16 07:53:50 -0400  400) </p><p><lb rend="displayNum" n="300" />kai\ d' a)/n e)pi\ <note n="1" place="unspecified" anchored="yes">e)/ti C; read e)/ti prote/rw| </note> prote/rw| ge, qala/ssh| polla\ peponqw/s,
de40680a (Stephen Sansom 2020-03-12 21:13:16 -0400  401) <lb rend="displayNum" n="301" />to/con o(/t' h)e/lios kai/ei kai\ r(u/tora *to/cou,
de40680a (Stephen Sansom 2020-03-12 21:13:16 -0400  402) <lb rend="displayNum" n="302" />e(spe/rios kata/goio, pepoiqw\s ou)ke/ti nukti/.
...
```

There are also log and blame tools in GitHub. For log, go to https://github.com/sasansom/sedes/blob/master/corpus/aratus.xml and click "History" to get
https://github.com/sasansom/sedes/commits/master/corpus/aratus.xml
Or click "Blame" to get
https://github.com/sasansom/sedes/blame/master/corpus/aratus.xml
