### ISSUE TITLE
Add a transform-ultima fallback step to the lemmatizer

### ISSUE THREAD

**Issue by whoopsedesy** [sasansom/sedes#29]
@sasansom informs me that the most common failure in `lemma.lookup` is a failure to find a lemma for words that have a grave accent on the ultima (last syllable). Many of these words would be lemmatized correctly if the grave accent were an acute accent. Another possible case is that an acute accent can be tried again with no accent at all. We can add a fallback: if the first attempt at lemmatization fails, and a grave→acute or acute→none transformation is possible, try again with the transformed string.

**Comment by whoopsedesy** [comment]
Pull request #47 has an implementation of this idea. Unfortunately, it hardly has an effect: it changes the lemma of only 3 distinct words, with 28 occurrences total.

|word|old lemma|new lemma|occurrences|
|:---|:--------|:--------|:----------|
|διοτρεφές|διοτρεφές|διοτρεφες|Hom.Hymn 4.533, Il. 7.109, Il. 11.648, Il. 11.653, Il. 21.223, Il. 23.581, Il. 24.635, Od. 4.138, Od. 4.156, Od. 4.291, Od. 4.316, Od. 4.391, Od. 10.266, Od. 10.419, Od. 15.64, Od. 15.87, Od. 15.155, Od. 15.167, Od. 15.199, Od. 22.136, Od. 24.122, Sh. 118|
|εὐρυσθενές|εὐρυσθενές|εὐρυσθενες|Il. 7.455, Il. 8.201, Od. 13.140|
|θαλείῃ|θαλείῃ|θαλειῃ|Od. 8.76, Od. 8.99, W.D. 742|

I gather that you expected a larger effect. Notably, none of the `OVERRIDES` in lemma.py are made obsolete by the ultima transformation.

Can you suggest a word that is currently not lemmatized correctly, but that you think would be lemmatized correctly with a transform-ultima step? As of ffb69dfa7128793f2116dd8a8a64458fafa568e9 in the master branch, I added a command-line mode to lemma.py, so you can test lemmatization of single words without having to put them in a TEI file:
```
$ python3 src/lemma.py ἄνδρα μοι ἔννεπε μοῦσα πολύτροπον ὃς μάλα πολλὰ
ἄνδρα	ἀνήρ
μοι	ἐγώ
ἔννεπε	ἐνέπω
μοῦσα	μοῦσα
πολύτροπον	πολύτροπος
ὃς	ὅς
μάλα	μάλα
πολλὰ	πολύς
```

<details>
<summary>Commands to view changed lemmata</summary>
<pre>
git checkout master && make expectancy.all.csv
src/join-expectancy corpus/*.csv expectancy.all.csv &gt; joined.all.1.csv
git checkout transform-lemmata && make expectancy.all.csv
src/join-expectancy corpus/*.csv expectancy.all.csv &gt; joined.all.2.csv
diff -u joined.all.1.csv joined.all.2.csv
</pre>
</details>

**Comment by sasansom** [comment]
This is curious. I've scrolled down the lemmata in expectancy.all and found a few example of words that are incorrectly lemmatized that I presume would be lemmatized correctly with a transform-ultima step (I've also checked these using the command-line mode to lemma.py):

These should be ἀγαθός ("good, noble"):

`% python3 src/lemma.py ἀγαθὴν
ἀγαθὴν	ἀγαθὴν`

`% python3 src/lemma.py ἀγαθὰς
ἀγαθὰς	ἀγαθὰς`

This should be ἀγακλεής ("famous"):

`% python3 src/lemma.py ἀγακλεὲς
ἀγακλεὲς	ἀγακλεὲς`

This should be ἀγανός ("gentle, mild"):

`% python3 src/lemma.py ἀγανὸς  
ἀγανὸς	ἀγανὸς`

This should be ἀγκών ("elbow"):

`% python3 src/lemma.py ἀγκὼν 
ἀγκὼν	ἀγκὼν`

Perhaps there is a problem with how the lemmatizer deals with adjectives, such as the first three sample lemmata above, but there's also a problem with nouns, such as the last example.

**Comment by whoopsedesy** [comment]
Thanks for your help on this. I found the source of the problem. It is that the CLTK backoff lemmatizer has a [last-resort identity lemmatizer](https://github.com/cltk/cltk/blob/de3f4fb72ed557101538e215b0e8096ad7ccb811/cltk/lemmatize/greek/backoff.py#L57), which means that it can (almost) never fail to return a lemma. (The exceptions, words for which it may not return a lemma, are those affected by https://github.com/cltk/cltk/issues/1051.) The transformation algorithm was meant to try each possible ultima transformation in turn (starting with the untransformed original word), and exit with the first one for which the CLTK backoff lemmatizer returned a lemma. But because the CLTK lemmatizer (almost) always returns a lemma, it (almost) never got past the untransformed word.

I should have spotted this right away, because the word διοτρεφές in https://github.com/sasansom/sedes/issues/29#issuecomment-788362469 is the same I cited in https://github.com/cltk/cltk/issues/1051.

The fix in https://github.com/sasansom/sedes/commit/407d91a724d44ed73aaa6abbb6369cfb8c4a8a46 is to inspect the result of CLTK lemmatization: if the returned lemma came from `IdentityLemmatizer`, we ignore it an try the next ultima transformation. We incorporate our own last-resort identity lemma in the case where all transformations fail to return a lemma.

This is the list of all 4,225 words whose lemma changes, along with the frequency of each word:
https://gist.github.com/whoopsedesy/4d498a41ff29136d34ff19fc648e7be4

Here are the 20 most frequently occurring words whose lemma changes:
|count|word|old lemma|new lemma|
|----:|:---|:--------|:--------|
|70|ποδὸς|ποδὸς|πούς|
|63|τὺ|τὺ|σύ|
|49|ἀχαιοὺς|ἀχαιοὺς|ἀχαιός|
|48|δαναοὶ|δαναοὶ|δαναός|
|47|φυτὸν|φυτὸν|φυτός|
|40|ἀγλαὸν|ἀγλαὸν|ἀγλαός|
|38|κλυτὸν|κλυτὸν|κλυτός|
|37|τεὸς|τεὸς|τεός|
|36|ἰνδὸν|ἰνδὸν|ἰνδός|
|34|ναὶ|ναὶ|ναί|
|34|μαζὸν|μαζὸν|μαστός|
|33|πτερὸν|πτερὸν|πτερόν|
|33|ἀχιλεὺς|ἀχιλεὺς|ἀχιλλεύς|
|32|ποτὸν|ποτὸν|πρόσειμι1|
|32|ἐνυὼ|ἐνυὼ|ἐνυώ|
|32|ἀλεγεινὸν|ἀλεγεινὸν|ἀλεγεινός|
|30|ἰνδὸς|ἰνδὸς|ἰνδός|
|29|στοιχηδὸν|στοιχηδὸν|στοιχηδόν|
|29|παρθενικὴ|παρθενικὴ|παρθενική|
|29|οὕνεκά|οὕνεκά|οὕνεκα|
