### ISSUE TITLE
Investigate Beta Code `ui(=)` in quintussmyrnaeus

### ISSUE THREAD

**Issue by whoopsedesy** [sasansom/sedes#46]
Working on #45, I found some words that have both rough breathing `(` and smooth breathing `)` diacritics. They are all in quintussmyrnaeus and all the word `ui(=)`. I'm wondering if this is a case like #11 where it's being used as a special kind of marker rather than actual Beta Code.

* [Q.S. 1.668](https://sasansom.github.io/sedes/quintussmyrnaeus.html#book-1-line-668)
  `o)/fra ti kai\ *phlh=os a)mu/monos ui(=) a)kaxh/sh|.`
* [Q.S. 7.170](https://sasansom.github.io/sedes/quintussmyrnaeus.html#book-7-line-170)
  `eu(=ron d' ui(=) *)axilh=os e(ou= propa/roiqe do/moio,`
* [Q.S. 7.723](https://sasansom.github.io/sedes/quintussmyrnaeus.html#book-7-line-723)
  `kai\ d' au)th\ *brishi/s, o(/t' e)/draken ui(=) *)axilh=os,`
* [Q.S. 8.172](https://sasansom.github.io/sedes/quintussmyrnaeus.html#book-8-line-172)
  `a)/sxeton ui(=) *)axelh=os, e)pei/ r(a/ min o)tru/neske`
* [Q.S. 9.26](https://sasansom.github.io/sedes/quintussmyrnaeus.html#book-9-line-26)
  `*trw=es o(mw=s teke/essi, dai+/frona d' ui(=) *)axilh=os`
* [Q.S. 9.305](https://sasansom.github.io/sedes/quintussmyrnaeus.html#book-9-line-305)
  `*)argei/ois w(/rmaine balei=n qrasu\n ui(=) *)axilh=os`
* [Q.S. 9.313](https://sasansom.github.io/sedes/quintussmyrnaeus.html#book-9-line-313)
  `i)/sxe ko/ton, kai\ mh/ti pelw/rion ui(=) *)axilh=os`
* [Q.S. 13.222](https://sasansom.github.io/sedes/quintussmyrnaeus.html#book-13-line-222)
  `e(rkei/ou poti\ bwmo/n: o( d' w(s i)/den ui(=) *)axilh=os,`

**Comment by sasansom** [comment]
I appears that these represent υἷ' and that they incorrectly use Beta Code smooth breathing `)` to stand for the apostrophe (indicating elision). Correct encoding of this word elsewhere uses `ui(='` (e.g. Argon. 4.117, Il. 13.185).
