### ISSUE TITLE
Check Cardo font for combing rho and spiritus asper

### ISSUE THREAD

**Issue by sasansom** [sasansom/sedes#50]
The html files produce a combined rho and rough breathing as Unicode [U+1FE5 GREEK SMALL LETTER RHO WITH DASIA  (ῥ)](https://www.unicode.org/charts/PDF/U1F00.pdf#page=2), but when a browser opens the file it does not combine. For example, see line four of example from the Shield at Issue #45. 

This appears to be a problem with the Cardo font, because the default font combines successfully.

**Comment by whoopsedesy** [comment]
I think this is just a bug in the Cardo font. When I open up U+1FE5 in FontForge, the glyph just looks like that:

![fontforge-cardo-1fe5](https://user-images.githubusercontent.com/53617134/111711842-778fd280-8844-11eb-9e89-f482a1d201f5.png)

The same phenomenon affects U+1FE4 GREEK SMALL LETTER RHO WITH PSILI and U+1FEC GREEK CAPITAL LETTER RHO WITH DASIA.

![fontforge-cardo-palette](https://user-images.githubusercontent.com/53617134/111711996-b887e700-8844-11eb-8a52-9b7d8e010f5e.png)

I found a few examples online of people mentioning the same problem:
* http://blogs.dickinson.edu/dcc/2015/02/03/goodells-school-grammar-of-attic-greek/
  > The font, New Athena, was likewise chosen for readability. Normally we would have used Cardo, but the issue with the character “rho + rough breathing” in Cardo has still not been resolved.
* https://latex.org/forum/viewtopic.php?t=32043
  > Well, there seems to be some peculiarity with the Cardo font that is triggering the issue. A couple of other fonts that I have just tried are working fine (Linux Libertine O and GFS Artemisia).

We have a few options:
1. Contact [David J. Perry](http://scholarsfonts.net/contact.html), the author of Cardo, to report the problem and see if there is the possibility of a fix. (We should do this in any case.)
2. Switch to a different font.
3. We are already [subsetting the full font](https://github.com/sasansom/sedes/blob/04925d49fd0d7c9111271b149de175bb9e4146cc/fonts/subset-greek.ff) to exclude all but Greek characters; we could additionally exclude U+1FE4, U+1FE5, and U+1FEC, and see if the text renderer (i.e., browser) does a better job of placing the diacritic. This is a bit of a hack, but it's easy to try.
4. We could make an exception to [our usual NFC Unicode normalization](https://github.com/sasansom/sedes/issues/38) for HTML output and decompose U+1FE5 → U+03C1 + U+0314 (mutatis mutandis for the other characters). This option is too horrible to contemplate.

I will try option 3 first.

**Comment by whoopsedesy** [comment]
> 3. We are already [subsetting the full font](https://github.com/sasansom/sedes/blob/04925d49fd0d7c9111271b149de175bb9e4146cc/fonts/subset-greek.ff) to exclude all but Greek characters; we could additionally exclude U+1FE4, U+1FE5, and U+1FEC, and see if the text renderer (i.e., browser) does a better job of placing the diacritic. This is a bit of a hack, but it's easy to try.

This idea doesn't really work. Rather than compose the glyph using components from Cardo, the browser pulls a precomposed glyph from some other system font (here, DejaVu Serif):

![shield-4](https://user-images.githubusercontent.com/53617134/111914114-a71f2480-8a68-11eb-91b9-4aa1ad5c43c4.gif)
![shield-28](https://user-images.githubusercontent.com/53617134/111914121-ab4b4200-8a68-11eb-9e0f-1274639f6125.gif)

This is what I did to exclude the glyphs from the font:

```diff
index b9b5ffa..63a2a64 100644
--- a/fonts/subset-greek.ff
+++ b/fonts/subset-greek.ff
@@ -1,10 +1,16 @@
 # Subset a font to Greek letters.
 # fontforge -lang ff -script subset-greek.ff input.ttf output.woff
 Open($1)
 SelectNone();
 SelectMore(0u0370, 0u03ff); # Greek and Coptic
 SelectMore(0u1f00, 0u1fff); # Greek Extended
+
+# Remove "rho with breathing mark" glyphs, which have the mark placed
+# incorrectly. Rely on the text renderer to compose these glyphs as needed.
+# https://github.com/sasansom/sedes/issues/50
+SelectFewerSingletons(0u1fe4, 0u1fe5, 0u1fec);
+
 SelectInvert();
 DetachAndRemoveGlyphs();
 Generate($2);
 Quit(0);
```

Incidentally, the same thing happens if, rather than excluding glyphs from the font files, you exclude them from the [`unicode-range`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/unicode-range) descriptor in CSS.

```diff
--- web-demo/shield.1.html      2021-03-21 11:14:32.988087596 -0600
+++ web-demo/shield.html        2021-03-21 11:15:34.300271147 -0600
@@ -10,7 +10,7 @@
     font-weight: 400;
     font-display: swap;
     src: local("Cardo Regular"), local("Cardo-Regular"), url(fonts/Cardo-Regular.woff) format("woff2");
-    unicode-range: U+0370-03FF, U+1F00-1FFF;
+    unicode-range: U+0370-03FF, U+1F00-1FE3, U+1FE6-1FEB, U+1FED-1FFF;
 }
 @font-face {
     font-family: "Cardo";
@@ -18,7 +18,7 @@
     font-weight: 400;
     font-display: swap;
     src: local("Cardo Italic"), local("Cardo-Italic"), url(fonts/Cardo-Italic.woff) format("woff2");
-    unicode-range: U+0370-03FF, U+1F00-1FFF;
+    unicode-range: U+0370-03FF, U+1F00-1FE3, U+1FE6-1FEB, U+1FED-1FFF;
 }
 @font-face {
     font-family: "Cardo";
@@ -26,7 +26,7 @@
     font-weight: 700;
     font-display: swap;
     src: local("Cardo Bold"), local("Cardo-Bold"), url(fonts/Cardo-Bold.woff) format("woff2");
-    unicode-range: U+0370-03FF, U+1F00-1FFF;
+    unicode-range: U+0370-03FF, U+1F00-1FE3, U+1FE6-1FEB, U+1FED-1FFF;
 }
 
 header {
```

**Comment by whoopsedesy** [comment]
> 4. We could make an exception to [our usual NFC Unicode normalization](https://github.com/sasansom/sedes/issues/38) for HTML output and decompose U+1FE5 → U+03C1 + U+0314

This doesn't work either; I tried it in Firefox and Chromium and it still uses the glyph with the diacritic hanging off to the left.

**Comment by whoopsedesy** [comment]
The downgrade to Cardo 0.99 in #56 seems to have incidentally fixed this.

![shield-4-cardo99](https://user-images.githubusercontent.com/53617134/114760841-4f19cc00-9d4f-11eb-8a87-d2511f1f0ced.png)
![shield-28-cardo99](https://user-images.githubusercontent.com/53617134/114760849-517c2600-9d4f-11eb-927e-b773c95809ad.png)
![argonautica-1 929-cardo99](https://user-images.githubusercontent.com/53617134/114760859-53de8000-9d4f-11eb-94c2-7e65adb88f11.png)
