### ISSUE TITLE
Investigate Argon. 1.70 scansion of ἀνδράσιν as – – –

### ISSUE THREAD

**Issue by whoopsedesy** [sasansom/sedes#65]
https://sasansom.github.io/sedes/argonautica.html#book-1-line-70-word-4 ([archive](https://web.archive.org/web/20210609175318/https://sasansom.github.io/sedes/argonautica.html#book-1-line-70-word-4))

**Comment by sasansom** [comment]
It should scan –⏑⏑. I've now fixed it in known.py.
