### ISSUE TITLE
Clean up in-band square brackets in homerichymns

### ISSUE THREAD

**Issue by whoopsedesy** [sasansom/sedes#85]
There are places where the text is marked up with literal `[` and `]` characters (presumably copied from the source book), rather than proper semantic TEI markup. This is causing problems especially for analysis of metrical shapes, as the brackets are considered part of the word.

https://github.com/sasansom/sedes/blob/a3721082fb71a0f6ec3487f65b9108caf8676caf/corpus/homerichymns.xml#L541-L545

One option is to simply delete the brackets.

A perhaps better solution is to replace the brackets with TEI markup that means the same and that we can still process without losing information. The Perseus 5.0 text uses the TEI [`supplied`](https://teic.github.io/TEI/ref-supplied.html) element, which "signifies text supplied by the transcriber or editor for any reason; for example because the original cannot be read due to physical damage, or because of an obvious omission by the author or scribe." We'll have to add support to the TEI parser for `supplied`.

https://github.com/PerseusDL/canonical-greekLit/blob/ca2e778d60de5f670b77870b53df405d30593115/data/tlg0013/tlg002/tlg0013.tlg002.perseus-grc2.xml#L501-L505
```xml
            <l n="385">νηοῖο προπάροιθε θυώδεος· <milestone unit="Para" ed="P"/>ἣ δὲ ἰδοῦσα </l>
            <l n="386">ἤιξʼ, ἠύτε μαινὰς ὄρος κάτα δάσκιον ὕλῃ. </l>
            <l n="387">Περσεφόνη δʼ ἑτέρ<supplied reason="lost">ωθεν ἐπεὶ ἴδεν ὄμματα καλὰ</supplied> </l>
            <l n="388">μητρὸς ἑῆς κατʼ <supplied reason="lost">ἄρʼ ἥ γʼ ὄχεα προλιποῦσα καὶ ἵππους</supplied> </l>
            <l n="389">ἆλτο θέει<supplied reason="lost">ν, δειρῇ δέ οἱ ἔμπεσε ἀμφιχυθεῖσα·</supplied> </l>
```

**Comment by sasansom** [comment]
Fixed with commit a113060

**Comment by whoopsedesy** [comment]
#86 handled all the cases for which [`supplied`](https://teic.github.io/TEI/ref-supplied.html) was appropriate, but left [two instances of square brackets](https://github.com/sasansom/sedes/pull/86#issuecomment-1787334717):
* https://github.com/sasansom/sedes/blob/f9228fbf3763754221eea38aba28efb4c4ff7278/corpus/homerichymns.xml#L823-L825
  [Book scan](https://archive.org/details/L496HesiodHomericHymnsHomerica/page/333/mode/2up)
  [Perseus version](https://github.com/PerseusDL/canonical-greekLit/blob/ca2e778d60de5f670b77870b53df405d30593115/data/tlg0013/tlg003/tlg0013.tlg003.perseus-grc2.xml#L227-L231)
* https://github.com/sasansom/sedes/blob/f9228fbf3763754221eea38aba28efb4c4ff7278/corpus/homerichymns.xml#L2432
  [Book scan](https://archive.org/details/L496HesiodHomericHymnsHomerica/page/441/mode/2up)
  [Perseus version](https://github.com/PerseusDL/canonical-greekLit/blob/ca2e778d60de5f670b77870b53df405d30593115/data/tlg0013/tlg018/tlg0013.tlg018.perseus-grc2.xml#L100)

Perseus 5.0 uses the [`surplus`](https://teic.github.io/TEI/ref-surplus.html) element in both cases. (But also retains the square brackets.) Thoughts?

**Comment by whoopsedesy** [comment]
Talking today, it seems that the last two instances of square brackets do not cause a problem, as they are not considered part of a word. (Only when punctuation, like a bracket, is sandwiched between letters is it considered part of a word.) So calling this done.
